version: '3.8'

services:
  frontend:
    build:
      context: ./frontend-vue
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend-vue:/app
    environment:
      - VITE_API_URL=http://fastapi:8000
      - VITE_AUTH_URL=http://php:8080
    networks:
      - app-network
    depends_on:
      - fastapi
      - php

  fastapi:
    build:
      context: ./backend-fastapi
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend-fastapi:/app
      - music-storage:/app/storage
    environment:
      - DATABASE_URL=mariadb://root:password@mariadb/musicdb
      - REDIS_URL=redis://redis:6379/0
      - CELERY_BROKER_URL=redis://redis:6379/1
      - CELERY_RESULT_BACKEND=redis://redis:6379/2
    networks:
      - app-network
    depends_on:
      - mariadb
      - redis

  php:
    build:
      context: ./php-auth
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./php-auth:/var/www/html
    networks:
      - app-network

  mariadb:
    image: mariadb:latest
    container_name: mariadb
    ports:
      - "3306:3306"
    volumes:
      - ./mariadb-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=musicdb
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  celery:
    build:
      context: ./backend-fastapi
      dockerfile: Dockerfile
    command: celery -A app.worker worker --loglevel=info
    volumes:
      - ./backend-fastapi:/app
      - music-storage:/app/storage
    environment:
      - DATABASE_URL=mariadb://root:password@mariadb/musicdb
      - REDIS_URL=redis://redis:6379/0
      - CELERY_BROKER_URL=redis://redis:6379/1
      - CELERY_RESULT_BACKEND=redis://redis:6379/2
    networks:
      - app-network
    depends_on:
      - redis
      - mariadb

volumes:
  mariadb-data:
  redis-data:
  music-storage:

networks:
  app-network:
    driver: bridge